Finished log hours page for an event
hack4impact-calpoly/the-land-conservancy pull request #32
Opened 2022-02-14 05:02 UTC by Ritvik1121

Finished making the log hours page for an event. The page has the event description that uses props and an input with basic validation to input hours and then a submit button. I had my back arrow go back to the events page but let me know if that needs to be changed. Let me know if anything needs to be changed!

fixes #18

2022-02-15 22:03 UTC, marissadarnell requested changes
Hi @Ritvik1121 , 
Nice job on this component overall, it looks pretty good. I made a couple comments with some changes for you to make, but let me know if you have any questions on how to implement them.

2022-02-15 22:03 UTC, marissadarnell commented on frontend/src/components/pages/eventDesc.tsx
> +  font-size: 14px
change to `20px`

2022-02-15 22:03 UTC, marissadarnell commented on frontend/src/components/pages/logHours.tsx
> +`;
seems redundant, probably delete the query on lines 42-45

2022-02-15 22:03 UTC, marissadarnell commented on frontend/src/components/pages/logHours.tsx
> +      setSubmit('Hours have been submitted.');
(Recent request from our Land Conservancy rep) Also, display a message like: 

> "View your updated history [here]()."    


which has a `Link` that will navigate to the `past-shifts` page

2022-02-15 22:03 UTC, marissadarnell commented on frontend/src/components/pages/logHours.tsx
> +          <StyledButton onClick={submitHours}>Submit</StyledButton>
clear or disable the form on submit so users can't keep submitting after the first time

2022-02-15 22:03 UTC, marissadarnell commented on frontend/src/components/pages/logHours.tsx
> +            onBlur={validateHours}
add the `required` attribute, so users can't submit unless it's filled out

2022-02-15 22:03 UTC, marissadarnell commented on frontend/src/components/pages/logHours.tsx
> +          <StyledButton onClick={submitHours}>Submit</StyledButton>
instead of `onClick` here, add `type=submit`
then add `onSubmit={submitHours}` inside the `<form>`, you can call `submitHours` after the `preventDefault`

2022-02-20 05:42 UTC, Ritvik1121 commented
Hey Marissa, I have made the requested changes you asked for. Let me know if there is anything I need to fix with those!

2022-02-22 18:51 UTC, marissadarnell approved these changes
Hi @Ritvik1121 , thanks for making those requested changes. I'll merge this in momentarily.

2022-02-22 20:20 UTC, merged