Click event
hack4impact-calpoly/the-land-conservancy pull request #64
Opened 2022-04-01 04:12 UTC by bbmcmann

Clicking an event on the events page now navigates to the correct log hours page by event. Hovering over the event changes the background color as well. It does not work with the navbar component active, the pushed code has the navbar disabled on the events page. If there are any changes needed or other bug fixes I will work on those right away!

2022-04-05 03:40 UTC, marissadarnell requested changes
Hello hello! This overall looks good and seems to work just fine, nice job. I'm going to push the navbar changes onto here momentarily for you to work with. See my Slack message for more details on that, and of course please message me with questions, concerns, etc.

- [ ] undo all the z-index changes
- [ ] Fix navbar blocking screen for any other pages (if you inspect in the browser you can observe if it is blocking other components)

2022-04-05 03:40 UTC, marissadarnell commented on frontend/src/components/pages/events.tsx
> +  z-index: 100;
revert z-index changes

2022-04-05 03:40 UTC, marissadarnell commented on frontend/src/components/navigation/navComponents.tsx
> +
can probably remove this

2022-04-05 03:40 UTC, marissadarnell commented on frontend/src/components/pages/eventCard.tsx
> +  z-index: 99999999;
here as well

2022-04-05 03:40 UTC, marissadarnell commented on frontend/src/components/navigation/navBar.tsx
> +    <StyledWrapper>
can probably revert this

2022-04-09 19:01 UTC, bbmcmann commented
Reviewed the other pages, the navbar works on all the other pages it is needed on. The pages that currently have user interaction implemented on them work with he navbar attached. Thanks for figuring out that bug fix!

2022-04-11 22:58 UTC, merged